spring.application.name=Course_Manager

spring.datasource.url=jdbc:mysql://localhost:3307/course_manager?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456789

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

logging.level.org.springframework.security=DEBUG
logging.level.org.example.course_manager=DEBUG

app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwtExpirationMs=1800000
app.jwtRefreshExpirationMs=604800000

server.port=8081

# Cloudinary configuration
cloudinary.cloud-name=nguyenvinh
cloudinary.api-key=479881854182615
cloudinary.api-secret=rXxScrVf04KtmKYN8lW-wgvRUNA